### ISSUE TITLE
Create a 3D graph for a flight that is finished

### ISSUE THREAD

**Issue by novreisb** [wolfoerster/WFTools3D#1]
I saw your very interesting package and I would like to use it at my private wpf app. The question is if it is possible with the package to do something similar to the picture attached?
thanks
Luis 
![graph3d](https://github.com/user-attachments/assets/02757ac1-94ca-4804-9605-6cb2ebd68c5b)

**Comment by wolfoerster** [comment]
Hi Luis, for sure that's possible. In fact it would be very easy to do so. You just would have to store the camera position every n seconds. When the flight is finished there will be an array of m 3D positions. For every two subsequent positions  you can create two triangles using positions p[i] and p[i+1] and the projections of these points to the xy-plane.

Thank you for this interesting question. If you like, I can add this feature to the project.

Cheers,
Wolfgang

**Comment by novreisb** [comment]
Hi Wolfgang, thanks for your quick answer ... and excellent that can be done. I am an hobbyist programmer and for the first time I am using Github besides downloading code, so not sure if I executed the right steps. I created a repository with my sub-project and added you as a collaborator. 
There is a docx file with some comments
Thanks a lot
Luis

**Comment by wolfoerster** [comment]
Hi Luis, can you send me the link to your repo. I cannot find any in your account.

**Comment by novreisb** [comment]
Newbie issue? Sorry 
https://github.com/novreisb/greatWFTools3D

**Comment by novreisb** [comment]
If you need Conversion LatLong To Pixel XY, here a method
        private const double EarthRadius = 6378137;
        private const double MinLatitude = -85.05112878;
        private const double MaxLatitude = 85.05112878;
        private const double MinLongitude = -180;
        private const double MaxLongitude = 180;
 public List<int> LatLongToPixelXY(double latitude, double longitude, int levelOfDetail, out int pixelX, out int pixelY)
 {
     latitude = Clip(latitude, MinLatitude, MaxLatitude);
     longitude = Clip(longitude, MinLongitude, MaxLongitude);
     double x = (longitude + 180) / 360;
     double sinLatitude = Math.Sin(latitude * Math.PI / 180);
     double y = 0.5 - Math.Log((1 + sinLatitude) / (1 - sinLatitude)) / (4 * Math.PI);
     uint mapSize = MapSize(levelOfDetail);
     pixelX = (int)Clip(x * mapSize + 0.5, 0, mapSize - 1);
     pixelY = (int)Clip(y * mapSize + 0.5, 0, mapSize - 1);
     return new List<int> { pixelX, pixelY };
 }
  private static double Clip(double n, double minValue, double maxValue)
 {
     return Math.Min(Math.Max(n, minValue), maxValue);
 }
 public static uint MapSize(int levelOfDetail)
{
    return (uint)256 << levelOfDetail;
}

**Comment by wolfoerster** [comment]
Hi Luis, I just had a look at your code and I don't think that you need a 3D package to visualize a flight path on top of the Bings map. The map is 2D and even if the airplane positions have three coordinates (latitude, longitude and altitude), the altitude values are very small against the scaling of the map. And the airplane itself won't be visible in a map with an extend of several 100 km.

For sure it would be possible to create a 3D scene which shows a map in the xy-plane and which shows the 3D flight path that you want, but that will need a complete different approach and will take a bit of time.

If you like you can checkout branch 'flightpath' of my WFTools3D repo. If you start the demo and press the Enter key the camera position will be recorded every second. Fly around and press Enter again to stop recording and to create the flight path 3D object. Now switch to camera 3 (by pressing the 3-key) and you should see that object. As you can see in the code, class FlightPath is not that complex. Perhaps you can use it once you switch your code to really 3D.

I'm afraid that's all I can do for you.

Cheers,
Wolfgang

**Comment by novreisb** [comment]
Hi Wolfgang,
Thanks for your patience. Yes, I understand your  point.
I will do what you suggest.
Cheers and go on with your quite interesting projects. 
Luis

**Comment by novreisb** [comment]
sorry Wolfgang but I don't see any action with Enter. It hits  "default: e.Handled = false; return;". I am not an expert as you understood, but what am I missing here?
........................................
........................................
  case Key.D3: ActivateCamera(2); return;
  default: e.Handled = false; return;

**Comment by wolfoerster** [comment]
Switch to branch 'flightpath' and you can see the following in MainWindow.xaml.cs:

        protected override void OnKeyDown(KeyEventArgs e)
        {
            base.OnKeyDown(e);

            if (e.Key == Key.Escape)
                Close();

            else if (e.Key == Key.Enter)
                ToggleFlightPathMode();
        }

        private void ToggleFlightPathMode()
        {
            if (flightPathMode)
            {
                flightPathMode = false;
                var flightPath = new FlightPath();
                flightPath.Init(camPositions);
                scene.Models.Add(flightPath);
            }
            else
            {
                flightPathMode = true;
                camPositions = new List<Point3D>();
            }
        }

        bool flightPathMode;
        List<Point3D> camPositions;

So start flying, press Enter, fly around, press Enter again and a new 3D model will be added to the scene. Switch to another camera, e.g. camera 3 (by pressing the 3-key) to see it.

Have fun, Wolfgang
